### ISSUE TITLE
Tensorflow. _api.v2.config issue

### ISSUE THREAD

**Issue by AlexQT90** [cderinbogaz/inpredo#10]
Hello, 
thanks for your Work.
I I launched in Colab according to the instructions.  But it gives an error on Second Step.  
AttributeError:module 'Tensorflow. _api.v2.config' has no attribute 'experimental_list_devices' 
Can you fix it?  Or tell me what needs to be done to fix this.

Regards, 
Alex

**Comment by interzonez** [comment]
I'm having similar issues. In tensorflow_backend.py

In line 506 I changed:

```
_LOCAL_DEVICES = tf.config.experimental_list_devices()
```
to 

```
devices = tf.config.list_logical_devices()
_LOCAL_DEVICES = [x.name for x in devices]
```

**Comment by AlexQT90** [comment]
> I'm having similar issues. In tensorflow_backend.py
> 
> In line 506 I changed:
> 
> ```
> _LOCAL_DEVICES = tf.config.experimental_list_devices()
> ```
> 
> to
> 
> ```
> devices = tf.config.list_logical_devices()
> _LOCAL_DEVICES = [x.name for x in devices]
> ```

Thank you ,
I did as you said. It seems that the only code line was not 506. But anyway, another error comes out when starting the file train-binary.py: 
ValueError: Error when checking target: expected dense_2 to have shape (2,) but got array with shape (3,)

Regards,

**Comment by cderinbogaz** [comment]
Hello Alex, 

You can completely remove these lines, since these commands only run to be able to return how many GPU devices exists on the computer. It is not a part of the code which does the AI, more used for diagnostics.
