### ISSUE TITLE
Loading model to continue training?

### ISSUE THREAD

**Issue by GrahamboJangles** [cderinbogaz/inpredo#5]
Is there a way to load a model to continue training? I tried throwing in `load_model()` right before training starts but it doesn't seem to work.

**Comment by GrahamboJangles** [comment]
Also, [in this line](https://github.com/cderinbogaz/inpredo/blob/c02e4ff422f13136f08803b4eb795adb3be885e2/src/graphwerk.py#L10), why is the data flipped? Doesn't this mean that it will predict the prices in the reverse time?

**Comment by cderinbogaz** [comment]
Data needs to be flipped if it is in ascending order. When you are building the candle graphs with `graphwerk.py` you have to start with the data that is older. For example if the data is starting from day 1 and goes to day 5 then you don't need to flip the data. If its other way around then you need to flip it.

**Comment by cderinbogaz** [comment]
You have to load saved model and weights using `from keras.models import load_model

model.save('my_model.h5')  # creates a HDF5 file 'my_model.h5'
del model  # deletes the existing model

# returns a compiled model
# identical to the previous one
model = load_model('my_model.h5')`

Method to be able to load it before going on with more training.
