### ISSUE TITLE
High accuracy is caused by a bug in the image creation

### ISSUE THREAD

**Issue by chrisffm** [cderinbogaz/inpredo#8]
Hey there,

because rows from the .csv file are ordered in the opposite direction, we are actually predicting the past. This is caused by the following operation:

`pd = np.flipud(ad)`

Given the fact that the close from the current day is the open for the next day, the color of the last bar is actually showing the price for the next (last) day.

Best,
Chris

**Comment by cderinbogaz** [comment]
Hello!

This is depending on the format of the csv file. Some csv files with financial data start from past and go into today, some of them opposite.

I think a logic to implement an automated way of understanding this csv row order and then applying the flip logic would be cool to have.

You can make a pull request if you have an algorithm in mind
